### PR TITLE
Errors squashed and armv7 support removed.

### PR DESCRIPTION
**Pull request by DarknesGaming**
IF we make an app that only runs on 64-bit devices, what's the point in supporting armv7?

### CODE REVIEW

**Comment by DarknesGaming** [comment]
I almost forgot! I added iTunes File Sharing capabilities. You should be able to import files using iTunes now.
Edit: You'll have to add the LZMA Extractor yourself.

**Comment by DarknesGaming** [comment]
1 month ago, I sent a pull request. 1 month later, my work is STILL not added. This fixes the build errors, and deletes armv7 support so we can get Dolphin 5.0 onto our iOS devices. It also adds iTunes File Sharing.

**Comment by EmilSayahi** [comment]
The guy has basically given up on the project lol
Just fork it and continue improving, so we can get Dolphin 5.0 onto iOS

**Comment by thehawkmanlyguy** [comment]
A really good thing I am hoping for in the future is moga controller support I currently have a controller and it works great it would be awesome to see this on the app.

**Comment by MaquinaDelMisterio** [comment]
So, this project still alive?

**Comment by GingerOfOz** [comment]
Several development problems rose up.  First of all, it looks like the main branch of Dolphin got cold feet about the project, as 5.0 features were supposed to be integrated several months and yet no changes have occurred.  Will also had issues getting iOS to allow the emulator use use more RAM/ CPU, so someone with more experience is needed to get that up and running.  Will has also been developing a large portion of his free time working on Pokemon Go hacks, because there is a large community who wants that, rather than the few dozen that want to play GCN games on their iPhones.

The last issue, is that it really is unknown if playable FPS can be accomplished on iOS devices.  Very few android devices are able to run games at good speed, and iOS in general doesn't play well with others.  

Those are just my thoughts, but I believe it may be quite a while before this project gets updated, if it ever does.

**Comment by MaquinaDelMisterio** [comment]
So, by the moment still useless , right?

**Pull request merged**
